### ISSUE TITLE
Multiple signup with same username should be prohibited

### ISSUE THREAD

**Issue by rweics** [huangshan108/CareerNet#1]
Right now if the same email address is used to sign up the second time, it says "Account successfully created!". Maybe it should be changed so that it reminds the user to log in with existing account. In case the user has forgotten the password, it should allow the user to reset password. (Maybe 'change password' should be provided too?)

**Comment by huangshan108** [comment]
For now the Login/Signup feature is just there for the seek of functionality. Yes, we should definitely enforce this and I will do it along with resetting password.
